[settings]
locked = true
github.slsa = false
lockfile = true
experimental = true
paranoid = false
github.github_attestations = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false

[tools]
"github:ip7z/7zip" = "26.00"
"github:go-task/task" = "v3.49.1"

[tools."http:zig"]
version = "0.15.2"
url = 'https://ziglang.org/download/{{ version }}/zig-{{ arch(x64="x86_64", arm64="aarch64") }}-{{ os() }}-{{ version }}.tar.xz'
bin_path = 'zig-{{ arch(x64="x86_64", arm64="aarch64") }}-{{ os() }}-{{ version }}'

[tools."http:zig".platforms]
windows-x64 = { url = 'https://ziglang.org/download/{{ version }}/zig-x86_64-windows-{{ version }}.zip', bin_path = 'zig-x86_64-windows-{{ version }}' }
