#!/usr/bin/env -S mise tool-stub
bin = "docker"
strip_components = 1

[platforms.darwin-arm64]
url = "https://download.docker.com/mac/static/stable/aarch64/docker-27.4.0.tgz"

[platforms.darwin-amd64]
url = "https://download.docker.com/mac/static/stable/x86_64/docker-27.4.0.tgz"

[platforms.linux-amd64]
url = "https://download.docker.com/linux/static/stable/x86_64/docker-27.4.0.tgz"

[platforms.linux-arm64]
url = "https://download.docker.com/linux/static/stable/aarch64/docker-27.4.0.tgz"

[platforms.windows-amd64]
url = "https://download.docker.com/win/static/stable/x86_64/docker-27.4.0.zip"
