name: saytw
description: Install sayt (via saytw) with caching, then warm the binary cache.
inputs:
  repo-root:
    description: Repository root where saytw and saytw.ps1 live.
    required: false
    default: "."
  saytw-path:
    description: Optional path to saytw or saytw.ps1.
    required: false
    default: ""
  version:
    description: Semver (e.g., 0.0.17 or v0.0.17). Empty uses the wrapper default.
    required: false
    default: ""
  seed-dir:
    description: Directory to copy into the saytw cache before installing.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Cache saytw downloads
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/sayt
          ~/Library/Caches/sayt
          ~/.local/share/mise
          ~/Library/Application Support/mise
          ${{ env.LOCALAPPDATA }}\sayt
          ${{ env.LOCALAPPDATA }}\mise
        key: saytw-${{ runner.os }}-${{ hashFiles(format('{0}/saytw', inputs.repo-root), format('{0}/saytw.ps1', inputs.repo-root)) }}

    - name: Seed saytw cache (Unix)
      if: ${{ inputs.seed-dir != '' && runner.os != 'Windows' }}
      shell: bash
      run: |
        mkdir -p ~/.cache/sayt
        mkdir -p ~/Library/Caches/sayt
        cp -R "${{ inputs.seed-dir }}/." ~/.cache/sayt
        cp -R "${{ inputs.seed-dir }}/." ~/Library/Caches/sayt

    - name: Seed saytw cache (Windows)
      if: ${{ inputs.seed-dir != '' && runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $seedDir = "${{ inputs.seed-dir }}"
        $targetDir = Join-Path $env:LOCALAPPDATA "sayt"
        New-Item -ItemType Directory -Force -Path $targetDir | Out-Null
        Copy-Item -Path (Join-Path $seedDir "*") -Destination $targetDir -Recurse -Force

    - name: Install sayt (Unix)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      working-directory: ${{ inputs.repo-root }}
      run: |
        export SAYT_VERSION="${{ inputs.version }}"
        saytw_path="${{ inputs.saytw-path }}"

        if [ -x "$saytw_path" ]; then
          "$saytw_path" --help
        elif [ -x "./saytw" ]; then
          ./saytw --help
        else
          curl -fsSL https://raw.githubusercontent.com/bonisoft3/sayt/refs/heads/main/install | sh -s -- --help
        fi

        sayt_cache="${XDG_CACHE_HOME:-$HOME/.cache}/sayt"
        repo_root="${GITHUB_WORKSPACE}/${{ inputs.repo-root }}"
        mkdir -p "$repo_root"
        cp -f "$sayt_cache/sayt" "$repo_root/sayt"
        chmod +x "$repo_root/sayt"
        "$repo_root/sayt" --help

    - name: Install sayt (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      working-directory: ${{ inputs.repo-root }}
      run: |
        $repoRoot = Join-Path $env:GITHUB_WORKSPACE "${{ inputs.repo-root }}"
        $saytwPath = "${{ inputs.saytw-path }}"
        $env:SAYT_VERSION = "${{ inputs.version }}"

        if ($saytwPath -and (Test-Path $saytwPath)) {
          & $saytwPath --help
        } elseif (Test-Path "./saytw.ps1") {
          ./saytw.ps1 --help
        } else {
          $tempInstall = Join-Path $env:RUNNER_TEMP "sayt-install.ps1"
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/bonisoft3/sayt/refs/heads/main/install" -UseBasicParsing -OutFile $tempInstall
          & $tempInstall --help
        }

        $cacheDir = if ($env:LOCALAPPDATA) {
          Join-Path $env:LOCALAPPDATA "sayt"
        } elseif ($env:XDG_CACHE_HOME) {
          Join-Path $env:XDG_CACHE_HOME "sayt"
        } else {
          Join-Path $env:HOME ".cache/sayt"
        }

        $repoSayt = Join-Path $repoRoot "sayt.exe"
        Copy-Item -Path (Join-Path $cacheDir "sayt.exe") -Destination $repoSayt -Force
        Set-Location $repoRoot
        ./sayt --help
